name: AutoSave
main: net.milkbowl.autosave.AutoSave
version: 3.0.0dev-b000
author: Cereal
description: >
             Provides automatic world saves at defined intervals.  The focus
             of the plugin is to provide a method to flush changes to disk.

commands:
  autosave:
    description: Saves the world.
    aliases: save
